//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.29 at 12:59:47 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bankjava.com/contracts", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bankjava.contracts;
